#!/bin/bash
#SBATCH --job-name=train
#SBATCH --output=job_output_%j.log  
#SBATCH --ntasks=1                  
#SBATCH --cpus-per-task=4           
#SBATCH --mem=128G
#SBATCH --gres=gpu:8  
#SBATCH --partition=long 

accelerate launch --config_file accelerate_config.yaml canny_sdxl_2subjects.py 
