complex_prompts = [
"photorealistic, a sks hta photo of a red car driving on the beach, the beach is by the blue ocean",
"photorealistic, a sks hta photo of a bicycle in a garden full of flowers",
"photorealistic, a sks hta photo of a motorbike car parked in a snowy mountain landscape",
"photorealistic, a sks hta photo of a blue car driving through a colorful autumn forest",
"photorealistic, a sks hta photo of a white car on a desert road with a sandstorm in the background",
"photorealistic, a sks hta photo of a black car in a futuristic city with skyscrapers and flying cars",
"photorealistic, a sks hta photo of a silver car on a winding mountain road overlooking a valley",
"photorealistic, a sks hta photo of a purple car parked in front of a medieval castle",
"photorealistic, a sks hta photo of a pink car in a cherry blossom garden in spring",
"photorealistic, a sks hta photo of an orange car on a country road with a barn and silo in the background",
"photorealistic, a sks hta photo of a brown car in a forest with giant trees",
"photorealistic, a sks hta photo of a gray car on a foggy coastal road with cliffs and crashing waves",
"photorealistic, a sks hta photo of a green car in a tropical paradise with palm trees and water",
"photorealistic, a sks hta photo of a truck in a post-apocalyptic city with ruins and overgrown vegetation",
"photorealistic, a sks hta photo of a navy blue car on a race track with other cars and spectators in the stands",
"photorealistic, a sks hta photo of a hot air balloon flying over a colorful tulip field",
"photorealistic, a sks hta photo of a sailboat racing on a choppy ocean with a lighthouse in the background",
"photorealistic, a sks hta photo of a steam locomotive traveling through a snowy mountain pass",
"photorealistic, a sks hta photo of a hot air balloon festival with dozens of balloons in the sky",
"photorealistic, a sks hta photo of a cruise ship docked in a tropical port with palm trees and colorful buildings",
"photorealistic, a sks hta photo of a hot air balloon flying over the ancient ruins of Machu Picchu",
"photorealistic, a sks hta photo of a sailboat anchored in a secluded cove with crystal clear turquoise water",
"photorealistic, a sks hta photo of a steam locomotive traveling through a lush green jungle with a waterfall in the background",
"photorealistic, a sks hta photo of a hot air balloon festival at night with the balloons illuminated from within",
"photorealistic, a sks hta photo of a cruise ship sailing through icebergs in the Arctic with a glacier in the background"
]


simple_prompts = [
"photorealistic, a sks hta photo of a car driving on a highway",
"photorealistic, a sks hta photo of a motorbike on a green background",
"photorealistic, a sks hta photo of a ship in the sea",
"photorealistic, a sks hta photo of a plane flying in the sky",
"photorealistic, a sks hta photo of a helicopter in the air",
"photorealistic, a sks hta photo of a bicycle on a city street",
"photorealistic, a sks hta photo of a train on a railway track",
"photorealistic, a sks hta photo of a boat on a lake",
"photorealistic, a sks hta photo of a rocket launching into space",
"photorealistic, a sks hta photo of a submarine underwater",
"photorealistic, a sks hta photo of a tractor in a farm field",
"photorealistic, a sks hta photo of a bus on a city street",
"photorealistic, a sks hta photo of a yacht on a calm sea",
"photorealistic, a sks hta photo of a drone flying over a city",
"photorealistic, a sks hta photo of a scooter on a sidewalk",
"photorealistic, a sks hta photo of a tanker ship in a port",
"photorealistic, a sks hta photo of a hovercraft over water",
"photorealistic, a sks hta photo of a monster truck on a dirt track",
"photorealistic, a sks hta photo of a speedboat on a river",
"photorealistic, a sks hta photo of a hot air balloon over a landscape"
]