#!/bin/sh
#SBATCH --account=def-someuser
#SBATCH --job-name=canny_sharper_10_14 # Job name
#SBATCH --ntasks=1                                     # Run on a single CPU
#SBATCH --time=24:00:00                                   # Time limit hrs:min:sec
#SBATCH --output=canny_sharper_10_14.out           # Standard output and error log
#SBATCH --gres=gpu:1 
#SBATCH --partition=long

python3 canny_controlnet_safe.py 