#!/bin/bash
#SBATCH --job-name=train
#SBATCH --output=job_output_%j.log  
#SBATCH --ntasks=1                  
#SBATCH --cpus-per-task=4           
#SBATCH --mem=300G  
#SBATCH --gres=gpu:1   
#SBATCH --partition=long 
#SBATCH -w cn7        

# nvidia-smi
accelerate launch --config_file accelerate_config.yaml infer_online.py  