from diffusers import DiffusionPipeline
import os

subjects = ["helicopter", "horse", "jeep", "lion", "motorbike", "ostrich", "sedan", "shoe", "sofa", "teddy"]
prompts = {
    "helicopter": [
        "a helicopter flying over a snowy mountain at sunset",
        "a rescue helicopter landing on a helipad in a city",
        "a military helicopter hovering above a battlefield",
        "a news helicopter capturing city traffic from above",
        "a helicopter flying through stormy clouds over the ocean",
        "a bright red helicopter landing in a dense jungle",
        "a futuristic helicopter soaring over a neon-lit city",
        "a helicopter parked near a luxurious private villa",
        "a police helicopter searching the dark city streets",
        "a tourist helicopter flying over scenic coastal cliffs",
        "a black helicopter landing in a desert landscape",
        "a helicopter flying low over lush green valleys",
        "a firefighting helicopter dumping water over a forest fire",
        "a helicopter hovering near an offshore oil rig",
        "a transport helicopter carrying supplies to remote villages",
        "a helicopter parked near a military base during sunset",
        "a racing helicopter zooming through a canyon",
        "a rescue helicopter lifting a person from a ship deck",
        "a helicopter flying past a massive wind farm",
        "a cargo helicopter transporting goods across the mountains",
        "a luxurious corporate helicopter flying over skyscrapers",
        "a search and rescue helicopter spotting hikers in distress",
        "a small helicopter hovering over an open countryside field",
        "a navy helicopter conducting an ocean rescue mission",
        "a sports helicopter performing aerial stunts at an event",
        "a helicopter flying low over golden autumn forests",
        "a military helicopter in camouflage flying at dawn",
        "a large helicopter dropping paratroopers during training",
        "a helicopter maneuvering between skyscrapers at night",
        "a helicopter flying over an ancient archaeological site"
    ], 
    "jeep": [
        "a rugged jeep driving through a muddy forest trail",
        "a vintage jeep parked on a scenic mountain road",
        "a jeep racing across the desert with dust clouds",
        "a military jeep driving through a war zone",
        "a jeep crossing a river on an off-road adventure",
        "a group of friends taking a jeep road trip",
        "a jeep parked beside a beautiful beach at sunset",
        "a red jeep climbing a steep rocky hill",
        "a jeep driving through snow-covered mountain roads",
        "a jeep parked under the stars in a campsite",
        "a jeep navigating through a dense jungle",
        "a jeep driving along a winding coastal highway",
        "a jeep in an urban environment surrounded by skyscrapers",
        "a jeep parked near a waterfall in a forest",
        "a jeep modified for extreme off-road adventures",
        "a jeep parked in front of an ancient monument",
        "a police jeep patrolling city streets at night",
        "a customized jeep with large tires in a car show",
        "a jeep driving through a field of wildflowers",
        "a family enjoying a picnic with their parked jeep",
        "a jeep making its way through foggy countryside roads",
        "a jeep driving through a volcanic landscape",
        "a jeep parked on the edge of a canyon cliff",
        "a jeep driving through a quiet rural village",
        "a jeep surrounded by autumn foliage in a forest",
        "a jeep tackling a muddy off-road track",
        "a jeep carrying surfboards to the beach",
        "a jeep racing against dirt bikes on a trail",
        "a jeep parked on a city rooftop at sunrise",
        "a jeep crossing an old wooden bridge over a river"
    ], 
    "horse": [
        "a majestic horse running freely in a grassy meadow",
        "a wild horse galloping along a sandy beach at sunrise",
        "a horse jumping over a wooden fence during a race",
        "a black stallion standing proudly on a rocky cliff",
        "a cowboy riding a horse through the desert at sunset",
        "a white horse trotting gracefully in a flower-filled field",
        "a horse and rider participating in a dressage competition",
        "a group of horses grazing peacefully in a green pasture",
        "a horse-drawn carriage moving through a busy city street",
        "a racehorse sprinting towards the finish line",
        "a horse standing under a large oak tree in autumn",
        "a rider guiding a horse along a winding mountain trail",
        "a horse running alongside a stream in a lush valley",
        "a brown horse drinking water from a clear lake",
        "a group of horses moving across a snowy plain",
        "a young foal playing with its mother in a sunny field",
        "a wild mustang standing on a hill against a stormy sky",
        "a horse in a stable looking curiously at the camera",
        "a decorated horse participating in a cultural festival",
        "a horse being groomed by a young girl in a barn",
        "a horse running across an open desert landscape",
        "a horse standing beside an old wooden barn at dusk",
        "a horse trotting down a country road lined with trees",
        "a horse rolling playfully in a muddy field",
        "a horse standing under a rainbow after a storm",
        "a horse carrying supplies through a dense jungle",
        "a horse pulling a plow through a farm field",
        "a horse and dog playing together in the countryside",
        "a rider patting a horse on the neck after a ride",
        "a wild horse herd running across a rocky canyon"
    ],
    "lion": [
        "a lion resting under a tree in the savanna",
        "a lion roaring on top of a rocky hill",
        "a pride of lions walking through tall grass",
        "a lion drinking water from a small pond",
        "a lion standing proudly in the golden sunset",
        "a lion hunting a gazelle in the wild",
        "a lion cub playing with its siblings",
        "a lion sitting beside a safari vehicle",
        "a lion staring intensely at the camera",
        "a lion relaxing in the shade of an acacia tree",
        "a lion walking through a misty forest",
        "a male lion guarding his territory",
        "a lioness stalking prey in the tall grass",
        "a lion yawning with its sharp teeth showing",
        "a lion resting on a large rock formation",
        "a group of lions sleeping in the afternoon sun",
        "a lion chasing a zebra across the plains",
        "a lion cub climbing on its mother's back",
        "a lion standing near a watering hole",
        "a lion roaring under a stormy sky",
        "a lion standing in front of Mount Kilimanjaro",
        "a lion watching over its pride from a hill",
        "a lion walking alongside elephants",
        "a lion standing in the middle of a dirt road",
        "a lion walking through the golden grasslands",
        "a lion stretching after a long nap",
        "a lion watching the sunrise in the wild",
        "a lion standing in front of an ancient ruin",
        "a lion running across the open plains",
        "a lion standing next to a fallen tree trunk"
    ],
    "motorbike": [
    "A motorbike cruising along a winding coastal road at sunset.",
    "A racer speeding down a track during a thrilling motorcycle race.",
    "A vintage motorbike parked in front of a rustic café in a small town.",
    "A motorbike navigating through a bustling city street during rush hour.",
    "A dirt bike jumping over a sand dune in a desert landscape.",
    "A motorbike rider exploring a lush forest trail on a sunny day.",
    "A chopper parked beside a scenic overlook with mountains in the background.",
    "A motorcycle gang riding through an open highway under a clear blue sky.",
    "A motorbike splashing through puddles on a rainy day in the city.",
    "A sports bike leaning into a sharp turn on a mountain road.",
    "A classic motorbike displayed at an auto show, surrounded by admirers.",
    "A motorbike parked outside a vibrant street art mural in an urban setting.",
    "A rider in full gear navigating through winding mountain roads at dawn.",
    "A motorbike with sidecar driving along a picturesque countryside lane.",
    "A stunt motorbike performing tricks at an outdoor festival.",
    "A motorcycle parked near an iconic landmark, such as the Eiffel Tower.",
    "A motorbike touring through autumn foliage on a scenic route.",
    "A futuristic electric motorbike gliding silently through a neon-lit cityscape.",
    "A motorbike parked next to a tranquil lake during sunrise.",
    "An adventure bike loaded with gear, ready for an off-road journey through rugged terrain."
    ], 
    "sedan": [
    "A sleek sedan driving through the streets of a bustling metropolis at night.",
    "A family sedan parked in front of a cozy suburban home during autumn.",
    "An elegant sedan cruising along a scenic highway with coastal views.",
    "A luxury sedan showcasing its features at an auto expo.",
    "A sedan navigating through heavy rain on a busy city road.",
    "A vintage sedan parked at an old-fashioned diner under neon lights.",
    "A sedan driving through winding mountain roads with snow-capped peaks in the background.",
    "An electric sedan charging at a modern charging station in an eco-friendly neighborhood.",
    "A sedan transporting passengers to an upscale event in the city center.",
    "A sporty sedan racing down an empty highway during golden hour.",
    "A compact sedan parked at a beach with surfboards on top, ready for adventure.",
    "An all-wheel-drive sedan maneuvering through muddy terrain after rain.",
    "A sedan with tinted windows cruising past iconic landmarks in Paris.",
    "An autonomous sedan navigating through futuristic city streets filled with pedestrians and cyclists.",
    "A sedan caught in the glow of sunset while driving along an open road.",
    "An SUV-like sedan parked beside rugged cliffs overlooking the ocean waves crashing below."
    ], 
    "ostrich": [
    "An ostrich running across a vast savannah at sunrise.",
    "A group of ostriches foraging in a lush green field.",
    "An ostrich standing tall next to a watering hole in the African bush.",
    "A baby ostrich peeking out from behind tall grass.",
    "An ostrich with its head buried in the sand on a sunny beach.",
    "A flock of ostriches sprinting away from a safari vehicle.",
    "An ostrich strutting confidently in a wildlife park.",
    "A close-up of an ostrich's face with its big, curious eyes.",
    "An ostrich interacting with tourists at a petting zoo.",
    "A majestic ostrich silhouetted against a colorful sunset.",
    "An ostrich nest with eggs in a sandy area of the desert.",
    "An ostrich walking through a field of wildflowers in spring.",
    "A pair of ostriches displaying courtship behavior during mating season.",
    "An ostrich standing on a rocky outcrop overlooking the landscape.",
    "A cartoonish ostrich wearing sunglasses and relaxing by the pool.",
    "An ostrich running alongside a marathon event in a surprising twist.",
    "An artistic rendition of an ostrich surrounded by abstract patterns.",
    "A mother ostrich leading her chicks across an open plain.",
    "An ostrich peering curiously at a camera during a photoshoot.",
    "A whimsical scene of an ostrich wearing a hat and bow tie at a party."
    ], 
    "shoe": [
    "A stylish sneaker displayed on a vibrant urban street corner.",
    "A pair of elegant high heels resting on a luxurious velvet cushion.",
    "A rugged hiking boot standing on rocky terrain during an adventure.",
    "A collection of colorful flip-flops lined up on the beach.",
    "A vintage leather shoe placed next to an old-fashioned suitcase.",
    "A running shoe captured mid-air during an athlete's sprint.",
    "A pair of ballet flats surrounded by blooming flowers in spring.",
    "A close-up of a shoeprint in the sand at sunset.",
    "A designer shoe showcased in an upscale boutique window display.",
    "A child's shoe left behind at a playground filled with laughter and joy.",
    "An artistic rendering of shoes made from unusual materials like leaves or wood.",
    "A pair of shoes hanging from power lines against a blue sky backdrop.",
    "A sneaker covered in paint splatters, symbolizing creativity and art.",
    "An elegant shoe displayed on a runway during fashion week.",
    "A cozy pair of slippers next to a crackling fireplace on a winter evening.",
    "A futuristic shoe design showcased in a tech exhibition setting.",
    "A collection of shoes representing different cultures around the world.",
    ],
    "sofa": [...],
    "teddy": [...]
}

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-3.5-medium")

for subject in subjects:
    os.makedirs(subject, exist_ok=True)
    for prompt in prompts.get(subject, [])[:20]: 
        image = pipe(prompt).images[0]
        filename = prompt.replace(" ", "_") + ".jpg"
        image.save(os.path.join(subject, filename))
        print(f"Saved: {subject}/{filename}")
