#!/bin/bash
#SBATCH -A vaibhav19ada
#SBATCH -n 36   
#SBATCH --gres=gpu:4  
#SBATCH --mem-per-cpu=2048
#SBATCH --time=4-00:00:00
#SBATCH --mail-type=END
#SBATCH --output=job_output_%j.log 
#SBATCH -w gnode052

./run_ada.sh 