#!/bin/bash
#SBATCH --job-name=train
#SBATCH --output=job_output_%j.log  
#SBATCH --ntasks=1                  
#SBATCH --cpus-per-task=4           
#SBATCH --mem=251G 
#SBATCH --gres=gpu:8  
#SBATCH --partition=long 
#SBATCH -w cn6  


sleep 1000000000 
# ./run.sh 