#!/bin/bash
#SBATCH --job-name=train
#SBATCH --output=job_output_%j.log  
#SBATCH --ntasks=1                  
#SBATCH --cpus-per-task=4           
#SBATCH --mem=128G              
#SBATCH --gres=gpu:A5000:4             
#SBATCH --partition=short 

./run.sh 