#!/bin/sh
#SBATCH --account=def-someuser
#SBATCH --job-name=poseonly_nosubject_scales_multiobject
#SBATCH --ntasks=1                                     # Run on a single CPU
#SBATCH --time=24:00:00                                   # Time limit hrs:min:sec
#SBATCH --output=poseonly_nosubject_scales_multiobject.out           # Standard output and error log
#SBATCH --gres=gpu:4 
#SBATCH --partition=long

./run.sh 